project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description:
    Course Projects for STA 9750 at Baruch College
  site-url: "https://j-lin07.github.io/STA9750-2025-SPRINGv2/"
  navbar:
    background: primary
    search: false
    
format:
  html:
    theme: sketchy
    toc: false

editor:
  mode: source